version: '3.3'
services:
  db:
    env_file:
      - ../backend/foodgram/.env
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  
  backend:
    image: robin532/diplom-back:v1.0
    restart: always
    volumes:
      - static_data:/diplom/static/
      - media_data:/diplom/media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/.env


  frontend:
    image: robin532/diplom-front:v1.0
    volumes:
      - frontend_data:/app/build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - frontend_data:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_data:
  media_data:
  frontend_data:
