# Generated by Django 4.0 on 2021-12-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.customuser', verbose_name='Автор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.customuser', verbose_name='Подписчики')),
            ],
            options={
                'verbose_name': 'Подписчики',
                'verbose_name_plural': 'Подписчики',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique_follow'),
        ),
    ]
